# SPDX-FileCopyrightText: 2025 IObundle
#
# SPDX-License-Identifier: MIT

name: CI

# Set default shell as interactive (source ~/.bashrc)
defaults:
  run:
    shell: bash -ieo pipefail {0}

# Run only one instance of this workflow at a time
# cancel-in-progress: stop running workflow and run latest instead
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  # Allow manual workflow runs
  workflow_dispatch:

jobs:

  simulation:
    runs-on: self-hosted
    timeout-minutes: 30
    # run even if previous job failed
    if: ${{ !cancelled() }}
  
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: run test
        run: make sim-test
  
  ku040:
    runs-on: self-hosted
    timeout-minutes: 90
    if: ${{ !cancelled() }}
    needs: [ simulation ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: FPGA build and run with baremetal firmware
        run: make fpga-build fpga-run BOARD=iob_aes_ku040_db_g
      - name: FPGA run with Linux OS
        run: make fpga-run BOARD=iob_aes_ku040_db_g RUN_LINUX=1

  reuse:
    runs-on: self-hosted
    timeout-minutes: 3
    if: ${{ !cancelled() }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Clean untracked files and directories (like old submodules)
        run: git clean -ffdx
      - name: Check compliance with REUSE specification
        run: nix-shell --run "reuse lint"
